repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: no-commit-to-branch
        args: ['--pattern', '^(?!((new_dir|new_ex|bugfix)\/[a-zA-Z0-9\-]+)$).*']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
